homepage: "https://www.freerdp.com/"
main_repo: "https://github.com/FreeRDP/FreeRDP"
language: c
primary_contact: ""
builds_per_day: 4
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
