homepage: "https://github.com/openvenues/libpostal"
primary_contact: "alex.gaynor@gmail.com"
auto_ccs: []
language: c
architectures:
  - x86_64
sanitizers:
  - address
  - memory
  - undefined
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
main_repo: 'https://github.com/openvenues/libpostal.git'
