homepage: "https://github.com/apache/zookeeper"
language: jvm
primary_contact: ""
main_repo: "https://github.com/apache/zookeeper.git"
file_github_issue: false
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
