homepage: "https://curl.haxx.se/"
language: c
sanitizers:
  - address
  - undefined
  - memory
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
architectures:
  - x86_64
main_repo: 'https://github.com/curl/curl.git'
