homepage: "http://www.libpng.org/pub/png/libpng.html"
language: c
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
main_repo: 'https://github.com/pnggroup/libpng.git'
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

